//! Post-process rolldown IIFE bundles to fix ESM→CJS interop.
//!
//! rolldown's `__toCommonJS` wraps ESM modules into namespace objects:
//!   `{ default: Pool, __esModule: true }`
//! but CJS consumers expect `require('pg-pool')` to return the Pool class
//! directly. This module patches `__toCommonJS` in the generated bundle to
//! return the default export when it's a function/constructor.

use anyhow::Result;
use std::path::Path;

/// The original __toCommonJS pattern generated by rolldown (unminified).
const OLD_PATTERN: &str = "var __toCommonJS = (mod) => __hasOwnProp.call(mod, \"module.exports\") ? mod[\"module.exports\"] : __copyProps(__defProp({}, \"__esModule\", { value: true }), mod);";

/// Patched version that returns the default export directly when it's a
/// function/constructor, with named exports copied onto it via __copyProps.
/// This matches webpack-style CJS interop where `require('m')` returns the
/// default export and `require('m').namedExport` works.
const NEW_PATTERN: &str = "var __toCommonJS = (mod) => __hasOwnProp.call(mod, \"module.exports\") ? mod[\"module.exports\"] : typeof mod.default === \"function\" ? __copyProps(mod.default, mod, \"default\") : __copyProps(__defProp({}, \"__esModule\", { value: true }), mod);";

/// Patch `__toCommonJS` in the generated bundle file in-place.
///
/// Handles both unminified and minified output from rolldown. The minifier
/// may rename the parameter (`mod` → `U`), change quotes (`"` → `` ` ``),
/// compress whitespace, and replace `true` with `!0`.
pub(crate) fn patch_to_common_js(bundle_path: &Path) -> Result<()> {
    let content = std::fs::read_to_string(bundle_path)?;

    // Try exact match first (fastest path for unminified bundles)
    let content = if content.contains(OLD_PATTERN) {
        content.replace(OLD_PATTERN, NEW_PATTERN)
    } else {
        content
    };

    // Also scan for minified __toCommonJS definitions (grouped bundles
    // may have both unminified and minified copies).
    let patched = patch_minified_to_common_js(&content);
    if patched != content {
        std::fs::write(bundle_path, &patched)?;
    } else if content != std::fs::read_to_string(bundle_path)? {
        std::fs::write(bundle_path, &content)?;
    }

    Ok(())
}

/// Scan for minified `__toCommonJS` arrow function definitions and patch them
/// to return the default export directly when it's a function/constructor.
///
/// The minified pattern looks like:
///   `__toCommonJS=U=>__hasOwnProp.call(U,`module.exports`)?U[`module.exports`]:__copyProps(__defProp({},`__esModule`,{value:!0}),U)`
///
/// We detect the start marker `__toCommonJS=` followed by an arrow function,
/// extract the parameter name, then find and replace the `__copyProps(...)`
/// fallback branch with our typeof check.
fn patch_minified_to_common_js(content: &str) -> String {
    let marker = "__toCommonJS=";
    let mut result = String::with_capacity(content.len());
    let mut rest = content;

    while let Some(pos) = rest.find(marker) {
        // Copy everything before the marker
        result.push_str(&rest[..pos]);

        let after_marker = &rest[pos + marker.len()..];

        // Extract parameter name: could be `(U)=>` or `U=>`
        let (param, after_param) = if after_marker.starts_with('(') {
            // `(U)=>`
            if let Some(close) = after_marker.find(')') {
                let param = after_marker[1..close].trim();
                (param.to_string(), &after_marker[close + 1..])
            } else {
                result.push_str(marker);
                rest = after_marker;
                continue;
            }
        } else {
            // `U=>`
            let end = after_marker
                .find(|c: char| !c.is_alphanumeric() && c != '_' && c != '$')
                .unwrap_or(after_marker.len());
            if end == 0 {
                result.push_str(marker);
                rest = after_marker;
                continue;
            }
            (after_marker[..end].to_string(), &after_marker[end..])
        };

        // Verify this is an arrow function with __hasOwnProp
        if !after_param.starts_with("=>") {
            result.push_str(marker);
            rest = after_marker;
            continue;
        }

        // Find the end of this expression by matching balanced parentheses.
        // The pattern ends with `,PARAM)` where PARAM is the parameter name.
        // We need to find the __copyProps fallback (after the `:`).
        let arrow_body = &after_param[2..]; // skip `=>`

        // Find `:__copyProps(__defProp(` — the fallback branch
        let fallback_marker = ":__copyProps(__defProp(";
        if let Some(fallback_pos) = arrow_body.find(fallback_marker) {
            // Find the end of the entire ternary expression.
            // Count parens from `__copyProps(__defProp(` to find the matching close.
            let from_fallback = &arrow_body[fallback_pos + 1..]; // skip the `:`
            if let Some(end) = find_balanced_paren_end(from_fallback) {
                let original_fallback = &from_fallback[..end];
                let p = &param;

                // Build the patched version with typeof check
                let patched_fallback = format!(
                    "typeof {p}.default===`function`?__copyProps({p}.default,{p},`default`):{original_fallback}"
                );

                result.push_str(marker);
                result.push_str(&param);
                result.push_str("=>");
                result.push_str(&arrow_body[..fallback_pos + 1]); // ternary up to `:`
                result.push_str(&patched_fallback);
                rest = &from_fallback[end..];
                continue;
            }
        }

        // Couldn't parse — copy as-is
        result.push_str(marker);
        rest = after_marker;
    }

    result.push_str(rest);
    result
}

/// Find the end of a balanced parenthesized expression.
///
/// Starting from `__copyProps(__defProp({},...),...,PARAM)`, find the position
/// after the outermost closing `)`.
fn find_balanced_paren_end(s: &str) -> Option<usize> {
    let mut depth = 0i32;
    let mut in_string = false;
    let mut string_char = ' ';

    for (i, ch) in s.char_indices() {
        if in_string {
            if ch == string_char {
                in_string = false;
            }
            continue;
        }

        match ch {
            '"' | '\'' | '`' => {
                in_string = true;
                string_char = ch;
            }
            '(' | '{' | '[' => depth += 1,
            ')' | '}' | ']' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i + 1);
                }
            }
            _ => {}
        }
    }
    None
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn patches_to_common_js_pattern() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("bundle.js");
        std::fs::write(&file, format!("var x = 1;\n{OLD_PATTERN}\nvar y = 2;")).unwrap();

        patch_to_common_js(&file).unwrap();

        let result = std::fs::read_to_string(&file).unwrap();
        assert!(!result.contains(OLD_PATTERN));
        assert!(result.contains(NEW_PATTERN));
        assert!(result.contains("var x = 1;"));
        assert!(result.contains("var y = 2;"));
    }

    #[test]
    fn patches_minified_pattern() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("bundle.js");
        let minified = "foo(),__toCommonJS=U=>__hasOwnProp.call(U,`module.exports`)?U[`module.exports`]:__copyProps(__defProp({},`__esModule`,{value:!0}),U),bar()";
        std::fs::write(&file, minified).unwrap();

        patch_to_common_js(&file).unwrap();

        let result = std::fs::read_to_string(&file).unwrap();
        assert!(
            result.contains("typeof U.default===`function`"),
            "Should patch minified pattern. Got: {result}"
        );
        assert!(result.contains("foo()"));
        assert!(result.contains(",bar()"));
    }

    #[test]
    fn patches_minified_with_parens() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("bundle.js");
        let minified = "__toCommonJS=(U)=>__hasOwnProp.call(U,`module.exports`)?U[`module.exports`]:__copyProps(__defProp({},`__esModule`,{value:!0}),U);";
        std::fs::write(&file, minified).unwrap();

        patch_to_common_js(&file).unwrap();

        let result = std::fs::read_to_string(&file).unwrap();
        assert!(
            result.contains("typeof U.default===`function`"),
            "Should patch minified pattern with parens. Got: {result}"
        );
    }

    #[test]
    fn patches_multiple_iifes() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("bundle.js");
        let content = format!(
            "(function(){{ {OLD_PATTERN} }})();\n\
             (function(){{ __toCommonJS=X=>__hasOwnProp.call(X,`module.exports`)?X[`module.exports`]:__copyProps(__defProp({{}},`__esModule`,{{value:!0}}),X) }})();"
        );
        std::fs::write(&file, content).unwrap();

        patch_to_common_js(&file).unwrap();

        let result = std::fs::read_to_string(&file).unwrap();
        // First IIFE uses exact match path
        assert!(result.contains(NEW_PATTERN));
        // Second IIFE uses minified path
        assert!(result.contains("typeof X.default===`function`"));
    }

    #[test]
    fn no_op_when_pattern_absent() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("bundle.js");
        let content = "var x = 1; var y = 2;";
        std::fs::write(&file, content).unwrap();

        patch_to_common_js(&file).unwrap();

        assert_eq!(std::fs::read_to_string(&file).unwrap(), content);
    }
}
