//! Post-process rolldown IIFE bundles to fix ESM→CJS interop.
//!
//! rolldown's `__toCommonJS` wraps ESM modules into namespace objects:
//!   `{ default: Pool, __esModule: true }`
//! but CJS consumers expect `require('pg-pool')` to return the Pool class
//! directly. This module patches `__toCommonJS` in the generated bundle to
//! return the default export when it's a function/constructor.

use anyhow::Result;
use std::path::Path;

/// The original __toCommonJS pattern generated by rolldown.
const OLD_PATTERN: &str = "var __toCommonJS = (mod) => __hasOwnProp.call(mod, \"module.exports\") ? mod[\"module.exports\"] : __copyProps(__defProp({}, \"__esModule\", { value: true }), mod);";

/// Patched version that returns the default export directly when it's a
/// function/constructor, with named exports copied onto it via __copyProps.
/// This matches webpack-style CJS interop where `require('m')` returns the
/// default export and `require('m').namedExport` works.
const NEW_PATTERN: &str = "var __toCommonJS = (mod) => __hasOwnProp.call(mod, \"module.exports\") ? mod[\"module.exports\"] : typeof mod.default === \"function\" ? __copyProps(mod.default, mod, \"default\") : __copyProps(__defProp({}, \"__esModule\", { value: true }), mod);";

/// Patch `__toCommonJS` in the generated bundle file in-place.
pub(crate) fn patch_to_common_js(bundle_path: &Path) -> Result<()> {
    let content = std::fs::read_to_string(bundle_path)?;
    if content.contains(OLD_PATTERN) {
        let patched = content.replacen(OLD_PATTERN, NEW_PATTERN, 1);
        std::fs::write(bundle_path, patched)?;
    }
    Ok(())
}
