/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for creating a Rex instance. */
export interface RexOptions {
  /** Path to the project root directory (containing pages/). */
  root: string
  /** Whether to run in dev mode (enables HMR, error overlays). */
  dev?: boolean
}
/** Result from matching a route. */
export interface JsRouteMatch {
  /** The route pattern, e.g. "/blog/:slug" */
  pattern: string
  /** The module name, e.g. "blog/[slug]" */
  moduleName: string
  /** Matched params, e.g. { slug: "hello" } */
  params: Record<string, string>
}
/** Result from renderPage. */
export interface JsPageResult {
  /** Full HTML document. */
  html: string
  /** HTTP status code. */
  status: number
  /** Response headers. */
  headers: Array<JsHeaderPair>
}
/** A header key-value pair. */
export interface JsHeaderPair {
  key: string
  value: string
}
/**
 * Create a new Rex application instance.
 *
 * Scans the pages directory, builds bundles, initializes the V8 isolate pool,
 * and returns a ready-to-use RexInstance.
 *
 * ```js
 * const rex = await createRex({ root: './my-app' })
 * ```
 */
export declare function createRex(options: RexOptions): Promise<RexInstance>
/**
 * A Rex application instance backed by Rust's V8 isolate pool and SSR engine.
 *
 * Created via `createRex()`. Handles route matching, server-side rendering,
 * and request handling for Rex applications.
 */
export declare class RexInstance {
  /** Whether this instance is running in dev mode. */
  get isDev(): boolean
  /** The current build ID. */
  get buildId(): string
  /** The path to the static files directory (client JS/CSS bundles). */
  get staticDir(): string
  /**
   * Match a URL path against the route trie.
   *
   * Returns the matched route info with params, or null if no match.
   * ```js
   * const match = rex.matchRoute('/blog/hello')
   * // { pattern: '/blog/:slug', moduleName: 'blog/[slug]', params: { slug: 'hello' } }
   * ```
   */
  matchRoute(path: string): JsRouteMatch | null
  /** Run getServerSideProps for a given path and return the result as JSON. */
  getServerSideProps(path: string): Promise<any>
  /** Render a page to an HTML string with the given props. */
  renderToString(path: string, props: any): Promise<string>
  /** Render a full page (GSSP + SSR + document assembly). Returns HTML, status, and headers. */
  renderPage(path: string): Promise<JsPageResult>
  /**
   * Get a request handler function compatible with the Web Fetch API.
   *
   * Returns a function `(Request) => Promise<Response>` that handles all Rex routes.
   * Works with Bun.serve, Deno.serve, and Node.js 18+ (which all support Web Request/Response).
   *
   * ```js
   * const handler = rex.getRequestHandler()
   * Bun.serve({ fetch: handler })
   * ```
   */
  getRequestHandler(): (req: Request) => Promise<Response>
  /** Shut down the Rex instance, releasing V8 isolates and other resources. */
  close(): Promise<void>
}
